name = "prisma-cloud-docs"
main = "worker/dist/index.mjs"

account_id = "852dfa4ae1b0d579df29be65b986c101"
workers_dev = true

compatibility_date = "2022-06-13"
compatibility_flags = []

[build]
command = "node ./build.js"
cwd = "worker"
# watch_dir = "worker/src"

[vars]
CONTENT_UPSTREAM='https://main--prisma-cloud-docs-website--hlxsites.hlx.page'
# temp using PAN repo as adoc source
DOC_UPSTREAM='https://raw.githubusercontent.com'
DOC_REPO_OWNER='hlxsites'
DOC_REPO_NAME='prisma-cloud-docs'
DOC_REPO_REF='main'
DOC_REPO_ROOT_PATH='/docs'
BASE_PATH='/prisma/prisma-cloud'

[env.production.vars]
CONTENT_UPSTREAM='https://main--prisma-cloud-docs-website--hlxsites.hlx.live'
# temp using PAN repo as adoc source
DOC_UPSTREAM='https://raw.githubusercontent.com'
DOC_REPO_OWNER='hlxsites'
DOC_REPO_NAME='prisma-cloud-docs'
DOC_REPO_REF='main'
DOC_REPO_ROOT_PATH='/docs'
BASE_PATH='/prisma/prisma-cloud'
