name = "prisma-cloud-docs"
main = "worker/dist/index.mjs"

account_id = "852dfa4ae1b0d579df29be65b986c101"
workers_dev = true

compatibility_date = "2022-06-13"
compatibility_flags = []

[build]
command = "node ./build.js"
cwd = "worker"
watch_dir = "worker/src"


[env.stage.build]
command = "NODE_ENV=stage npm run build"

[env.production.build]
command = "NODE_ENV=production npm run build"

[vars]
# temp using PAN repo as adoc source
CONTENT_UPSTREAM='https://raw.githubusercontent.com'
CONTENT_REPO_OWNER='PaloAltoNetworks'
CONTENT_REPO_NAME='prisma-cloud-docs'
CONTENT_REPO_REF='master'
CONTENT_REPO_ROOT_PATH='/'