name: Preview changed docs

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Preview changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          json: true
          json_raw_format: true
          files: |
            docs/**/*.adoc
            docs/**/book.yml

      - name: Show preview if any *.adoc or book.yml in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |

            const { default: previewChanges } = await import('${{ github.workspace }}/bin/preview-changes.js')

            await previewChanges({
              github,
              context,
              changes: ${{ steps.changed-files-specific.outputs.all_changed_files }}
            });



