name: Publish changed docs

on:
  push:
    branches:
      - main

jobs:
  changedfiles:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "all<<$EOF" >> "$GITHUB_ENV"
          git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.event.after }} | xargs >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

  build:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{ needs.changedfiles.outputs.all }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run publish:batch ${{ needs.changedfiles.outputs.all }}