name: Sitemap

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: generate sitemaps
        run: ORIGIN='https://main--prisma-cloud-docs-website--hlxsites.hlx.live' npm run gen:sitemaps
      - name: push sitemaps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(sitemap): publish sitemaps [skip ci] [deploy]'
          branch: main
          file_pattern: 'prisma/prisma-cloud/docs/sitemaps/*.xml'
          commit_user_name: 'github-actions[bot]'
          commit_options: '--no-verify --allow-empty'
          push_options: '--force'
          disable_globbing: true